language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly
notifications:
  email: false
matrix:
  allow_failures:
    - os: osx
    - julia: 1.0
    - julia: nightly
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'using Pkg; Pkg.clone(pwd()); Pkg.test("KernelDensityEstimatePlotting"; coverage=true)'
after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("KernelDensityEstimatePlotting")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
